---
title: "Waterlogging Analysis"
author: "Hamish McLean"
date: "`r format(Sys.Date(), '%Y-%m-%d')`"
output: 
  html_document:
    toc: true
    toc_float: true
    highlight: tango
    theme: spacelab
    code_folding: hide
    # fig_caption: true
    # self_contained: false
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE) #, message = FALSE, warning = FALSE)
```

```{r load_packages}

library(car)
library(data.table)
library(DHARMa)
library(dplyr)
library(emmeans)
library(ggpubr)
library(glmmTMB)
library(here)
library(lme4)
library(performance)
library(readxl)

```

```{r constants}

# Set the working directory to the project root
# here::set_here()

# Set data and figures directories
data_dir    <- here("..", "Data")
figures_dir <- here("figures")

# Load custom functions
source(here("functions", "load_data.R"))

latte <- list(
  red = "#d20f39",
  yellow = "#df8e1d",
  green = "#40a02b",
  text = "#4c4f69"
)

```

## Load data

### Experiment 1

```{r load_data_E1}

e1_2023 <- load_data(
  data_dir, "2023 E1 growth measurements.xlsx",
  c(
    "d_spring", "d_fall", "h_spring", "h_fall", "health_fall",
    "mainstem", "peripheral", "inoc_points", "aborted", "inoc_cankers"
  )
)

# Combine diameter and height measurements
e1_2023[, diameter := coalesce(d_spring, d_fall)]
e1_2023[, height   := coalesce(h_spring, h_fall)]
e1_2023[, c("d_spring", "d_fall", "h_spring", "h_fall") := NULL]

# Rename health_fall to health
e1_2023[, health := health_fall][, health_fall := NULL]

# Calculate total cankers
e1_2023[,
  cankers := rowSums(.SD, na.rm = FALSE),
  .SDcols = c("mainstem", "peripheral")
]

e1_2024_cankers <- load_data(
  data_dir, "2024-09-23 E1 canker assessment.xlsx", "cankers"
)

e1_2024_growth <- load_data(
  data_dir, "2024-11 E1 growth measurements.xlsx",
  c("diameter", "height", "health")
)

# Combine E1 tables

common_cols <- intersect(colnames(e1_2023), colnames(e1_2024_cankers))
e1 <- merge(e1_2023, e1_2024_cankers, by = common_cols, all = TRUE)

common_cols <- intersect(colnames(e1_2024_cankers), colnames(e1_2024_growth))
e1 <- merge(e1, e1_2024_growth, by = common_cols, all = TRUE)

e1[, diameter := coalesce(diameter.x, diameter.y)][, c("diameter.x", "diameter.y") := NULL]
e1[, height := coalesce(height.x, height.y)][, c("height.x", "height.y") := NULL]
e1[, health := coalesce(health.x, health.y)][, c("health.x", "health.y") := NULL]

# Add experiment id column
e1[, experiment := "E1"]

```

### Experiment 2

```{r load_data_E2}

e2_2024_05 <- load_data(
  data_dir, "2024-05 E2 growth measurements.xlsx", "diameter"
)

e2_2024_09_cankers <- load_data(
  data_dir, "2024-09-24 E2 canker assessment.xlsx", c(
    "rasp_inoculations", "rasp_cankers",
    "leaf_scar_inoculations", "leaf_scar_cankers"
  )
)

e2_2024_12_growth <- load_data(
  data_dir, "2024-12 E2 growth measurements.xlsx",
  c("diameter", "height", "feather", "health")
)

# Combine E2 tables

e2 <- Reduce(
  function(x, y) {
    # Merge on common columns
    common_cols <- intersect(colnames(x), colnames(y))
    merge(x, y, by = common_cols, all = TRUE)
  },
  list(e2_2024_05, e2_2024_09_cankers, e2_2024_12_growth)
)

e2[, timepoint := as.factor(timepoint)]

# Add experiment id column
e2[, experiment := "E2"]

# Add height at T1 by subtracting feather at T2 from height at T2
e2 <- merge(
  e2,
  e2[(!is.na(height) & !is.na(feather)), .(tree, height = height - feather, timepoint = "T1")],
  by = c("tree", "timepoint"),
  all.x = TRUE
)
e2[, height := coalesce(height.x, height.y)][, c("height.x", "height.y") := NULL]

```

### Experiment 3

```{r load_data_E3}

e3_2024_10_growth <- load_data(
  data_dir, "2024-10 E3 growth measurements.xlsx", "data"
)

e3_2025_05_cankers <- load_data(
  data_dir, "2025-05 E3 canker assessment.xlsx", c(
    "inoculations", "cankers"
  )
)

# e3_2024_10_growth |> head()
# e3_2025_05_cankers |> head()

# Combine E3 tables

e3 <- Reduce(
  function(x, y) {
    # Merge on common columns
    common_cols <- intersect(colnames(x), colnames(y))
    merge(x, y, by = common_cols, all = TRUE)
  },
  list(e3_2024_10_growth, e3_2025_05_cankers)
)[, experiment := "E3"]

# e3 |> head()

```

### Experiment 4

```{r load_data_E4}

e4_2024_12_growth <- load_data(
  data_dir, "2024-12 E4 growth measurements.xlsx", "diameter"
)

e4_2025_05_cankers <- load_data(
  data_dir, "2025-05 E4 canker assessment.xlsx", c(
    "inoculations", "cankers"
  )
)

# e4_2024_12_growth |> head()
# e4_2025_05_cankers |> head()

# Combine E4 tables
e4 <- Reduce(
  function(x, y) {
    # Merge on common columns
    common_cols <- intersect(colnames(x), colnames(y))
    merge(x, y, by = common_cols, all = TRUE)
  },
  list(e4_2024_12_growth, e4_2025_05_cankers)
)[, experiment := "E4"]

# e4 |> head()

```

## Tree health

```{r tree_health}

#' @title Summarise tree health
#'
summarise_tree_health <- function(data) {

  # Check columns
  if (!all(c(
    "experiment", "timepoint", "duration", "health"
  ) %in% colnames(data))) {
    stop("Input data does not contain required columns.")
  }

  data_copy <- copy(data[, .(experiment, timepoint, duration, health)])

  # Combine health categories
  health_mapping <- list(
    healthy = c("healthy", "top_broken", "broken"),
    unhealthy = c("nearly_dead", "unhealthy", "top_dead")
  )
  data_copy[, health := fcase(
    health %in% health_mapping$healthy, "healthy",
    health %in% health_mapping$unhealthy, "unhealthy",
    rep(TRUE, .N), health # Keep other categories unchanged
  )]

  health_summary <- data_copy[!is.na(health), .N, by = .(
    experiment, timepoint, duration, health
  )]
  health_combinations <- CJ(
    experiment = unique(data_copy$experiment),
    timepoint = unique(data_copy$timepoint),
    duration = unique(data_copy$duration),
    health = c("healthy", "unhealthy", "dead", "missing")
  )
  health_summary <- merge(
    health_combinations,
    health_summary,
    by = c("experiment", "timepoint", "duration", "health"),
    all.x = TRUE
  )
  health_summary[is.na(N), N := 0] # Replace NA with 0 for missing combinations

  health_summary[, health := factor(
    health, levels = c("healthy", "unhealthy", "dead", "missing")
  )]

}

#' @title Summarise tree health
#'
summarise_tree_health <- function(data, by) {

  # Check columns
  if (!all(by %in% colnames(data))) {
    stop("Input data does not contain required columns.")
  }

  data_copy <- copy(data[, ..by])

  # Combine health categories
  health_mapping <- list(
    healthy = c("healthy", "top_broken", "broken"),
    unhealthy = c("nearly_dead", "unhealthy", "top_dead")
  )
  data_copy[, health := fcase(
    health %in% health_mapping$healthy, "healthy",
    health %in% health_mapping$unhealthy, "unhealthy",
    rep(TRUE, .N), health # Keep other categories unchanged
  )]
  health_levels <- c("healthy", "unhealthy", "dead", "missing")

  # Generate all combinations of by columns and health
  # comb_list <- lapply(by, function(col) {
  #   ifelse(col == "health", health_levels, unique(data_copy[[col]]))
  # })
  comb_list <- lapply(by, function(col) unique(data_copy[[col]]))
  names(comb_list) <- by
  comb_list$health <- c("healthy", "unhealthy", "dead", "missing")
  health_combinations <- do.call(CJ, comb_list)

  # Summarise health data
  health_summary <- data_copy[!is.na(health), .N, by = by]

  health_summary <- merge(
    health_combinations,
    health_summary,
    by = by,
    all.x = TRUE
  )

  health_summary[is.na(N), N := 0] # Replace NA with 0 for missing combinations

  # Reorder health factor levels
  health_summary[, health := factor(
    health, levels = health_levels
  )]

}

e1_health_summary <- summarise_tree_health(
  e1, c("experiment", "timepoint", "duration", "health")
)

e2_health_summary <- summarise_tree_health(
  e2, c("experiment", "timepoint", "duration", "health")
)

e3_health_summary <- summarise_tree_health(
  e3, c("experiment", "timepoint", "treatment", "genotype", "health")
)

e4_health_summary <- summarise_tree_health(
  e4, c("experiment", "timepoint", "season", "duration", "health")
)


plot_tree_health <- function(health_summary, facet_cols, facet_rows) {
  ggbarplot(
    health_summary,
    x = "timepoint",
    y = "N",
    fill = "health",
    color = "health",
    position = position_dodge(0.8),
    palette = c(
      healthy = latte$green,
      unhealthy = latte$yellow,
      dead = latte$red,
      missing = latte$text
    )
  ) +
    facet_grid(cols = vars(!!sym(facet_cols)), rows = vars(!!sym(facet_rows))) +
    labs(
      title = "Tree Health by Treatment",
      x = "Treatment Duration",
      y = "Number of Trees"
      # fill = "Health Category"
    ) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
    # theme_minimal()
}

# plot_tree_health(e1_health_summary)

# plot_tree_health(e2_health_summary)

plot_tree_health(
  bind_rows(e1_health_summary, e2_health_summary)[timepoint %in% c("T2", "T3")], 
  "duration", "experiment"
)

plot_tree_health(e3_health_summary[timepoint == "T2"], "treatment", "genotype")

plot_tree_health(e4_health_summary[timepoint == "T2"], "duration", "season")

```

## Tree health

```{r tree health}

# Combine E1 and E2

# Class all living trees as healthy
healthy <-  c(
  "healthy", "top_broken", "broken", "nearly_dead", "unhealthy", "top_dead"
)

# Summarise health data for E1 and E2 at T2
e1_e2_health <- rbind(e1, e2, fill = TRUE)[
  timepoint == "T2" & !is.na(health),
  .(healthy = sum(health %in% healthy), dead = sum(health == "dead")),
  by = .(experiment, block, duration)
][, experiment := factor(experiment)]

design <- y ~ experiment * duration + (1 | experiment / block)

health_model <- glmmTMB(
  update(design, cbind(healthy, dead) ~ .),
  data = e1_e2_health,
  family = betabinomial(link = "logit")
)

health_model <- glmer(
  update(design, cbind(healthy, dead) ~ .),
  data = e1_e2_health,
  family = binomial(link = "probit")
)

# Check model assumptions
check_model(health_model)
check_overdispersion(health_model)

sim <- simulateResiduals(health_model)
plot(sim)
testDispersion(sim)

summary(health_model)
Anova(health_model, type = 3)
# ranova(health_model, type = 3)
emmeans(health_model, ~ duration | experiment) |> plot()

```

## Data cleaning

Remove pots with 2 or more dead or missing trees.
Remove dead trees.
Remove E2 pot 33

```{r data_cleaning}

# Remove pots with 2 or more dead or missing trees
remove_dead_pots <- function(data) {
  pots_to_remove <- unique(data[
    health == "dead" | health == "missing", .N, by = .(pot, timepoint)
  ][N >= 2, .(pot)])

  cat(
    "Removed", nrow(pots_to_remove),
    "pots with 2 or more dead or missing trees\n\n"
  )

  data[!.(pots_to_remove), on = .(pot)]
}

e1 <- remove_dead_pots(e1)
e2 <- remove_dead_pots(e2)

# Remove dead trees
remove_dead_trees <- function(data) {
  trees_to_remove <- data[health == "dead" | health == "missing", tree]
  cat("Removed", length(trees_to_remove), "remaining dead or missing trees\n\n")
  data[!(tree %in% trees_to_remove), ]
}

e1 <- remove_dead_trees(e1)
e2 <- remove_dead_trees(e2)

# Remove dead trees
remove_dead_trees <- function(data) {
  trees_to_remove <- data[health == "dead" | health == "missing", pot]
  cat("Removed", length(trees_to_remove), "remaining dead or missing trees\n\n")
  data[!(pot %in% trees_to_remove), ]
}

e3 <- remove_dead_trees(e3)
e4 <- remove_dead_trees(e4)

# Remove trees which are missing at any timepoint
remove_corresponding <- function(data) {

}


# Remove E1 8 week duration
e1 <- e1[duration != 8]

# Remove E2 pot 33
e2 <- e2[pot != 33]

# Combine E1 and E2 data
e1_e2 <- rbind(e1, e2, fill = TRUE)

```

## Growth

```{r growth functions}

#' @title Summarise growth data
#'
summarise_growth <- function(data, measurement, remove_health = NULL) {
  # Check columns
  if (!all(c(
    "experiment", "timepoint", "duration", measurement
  ) %in% colnames(data))) {
    stop("Input data does not contain required columns.")
  }

  # Summarise data by measurement
  data[
    !is.na(get(measurement)) & !(health %in% remove_health),
    .(
      mean = mean(get(measurement), na.rm = TRUE),
      median = median(get(measurement), na.rm = TRUE),
      N = .N,
      sd = sd(get(measurement), na.rm = TRUE)
    ),
    by = .(experiment, timepoint, duration)
  ][, duration := factor(duration)]
}

#' @title Plot growth data
#'
plot_growth <- function(data, measurement) {
  ggline(
    data,
    x = "timepoint",
    y = "mean",
    color = "duration"
  ) +
    labs(
      title = paste(measurement, "by Treatment"),
      x = "Timepoint",
      y = measurement
    )
}

```

### Diameter

```{r diameter}

# E1 diameter
plot_growth(
  summarise_growth(e1, "diameter"),
  "diameter"
)

# E2 diameter
plot_growth(
  summarise_growth(e2, "diameter"),
  "diameter"
)

# Models

e1[, duration := factor(duration)]

design <- y ~ block + duration * timepoint + (1 | tree) + (1 | pot)

# E1 diameter

e1_diameter_model <- lmer(
  # diameter ~ duration + timepoint + duration:timepoint + (1 | block) + (1 | tree) + (1 | pot), # + (timepoint | tree),
  # update(design, paste0("log(", diameter, ")") ~ .),
  log(diameter) ~ block + duration * timepoint + (1 | tree) + (1 | pot),
  data = e1
)

# Check model assumptions
check_model(e1_diameter_model)

# Try a GLMM with gamma
e1_diameter_glmm <- glmer(
  update(design, diameter ~ .),
  data = e1,
  family = gaussian(link = "log")
)

plot(simulateResiduals(e1_diameter_glmm))

# Plot residuals vs fitted values
# plot(
#   fitted(e1_diameter_model), residuals(e1_diameter_model),
#     xlab = "Fitted Values", ylab = "Conditional Residuals",
#     main = "Residuals vs. Fitted"
# )
# abline(h = 0, col = latte$red, lty = 2)

# # Q-Q plot
# qqnorm(residuals(e1_diameter_model))
# qqline(residuals(e1_diameter_model), col = latte$red)

summary(e1_diameter_model)
Anova(e1_diameter_model, type = 3)
emmeans(e1_diameter_model, ~ duration | timepoint)
# emmeans(e1_diameter_model, pairwise ~ duration | timepoint)


e2_diameter_model <- lmer(
  log(diameter) ~ duration + timepoint + duration:timepoint + (1 | block) + (1 | tree) + (1 | pot), # + (timepoint | tree),
  data = e2[, duration := factor(duration)]
)

check_model(e2_diameter_model)

summary(e2_diameter_model)
Anova(e2_diameter_model, type = 3)
emmeans(e2_diameter_model, ~ duration | timepoint)


# E1 & E2 model

design <- y ~ experiment + duration + elapsed_years + experiment:duration + duration:elapsed_years + (1 | experiment / tree) + (1 | experiment / block)


e1_e2_diameter_model <- lmer(
  update(design, diameter ~ .),
  data = e1_e2[timepoint != "T3" & duration != 8]
)

check_model(e1_e2_diameter_model)
summary(e1_e2_diameter_model)
Anova(e1_e2_diameter_model, type = 3)
emmeans(e1_e2_diameter_model, pairwise ~ duration | experiment) |> plot()

```

### Height

```{r height}

top_removals <- c("top_broken", "top_missing")

# E1 height
plot_growth(
  summarise_growth(e1, "height", top_removals),
  "height"
)

# E1 height model
e1_height_model <- lmer(
  log(height) ~ duration + timepoint + duration:timepoint + (1 | block) + (1 | tree) + (1 | pot), # + (timepoint | tree),
  data = e1[!(health %in% top_removals), duration := factor(duration)]
)

# Check model assumptions
check_model(e1_height_model)

summary(e1_height_model)
Anova(e1_height_model, type = 3)
emmeans(e1_height_model, ~ duration | timepoint)

# E2 height
plot_growth(
  summarise_growth(e2, "height", top_removals),
  "height"
)

ggline(
  summarise_growth(e2, "height", top_removals),
  x = "timepoint",
  y = "median",
  color = "duration"
) +
  labs(
    title = "Height by Treatment",
    x = "Timepoint",
    y = "Height (cm)"
  )

e2_height_summary <- e2[
  !is.na(height) & !(health %in% top_removals),
  .(block, plot, duration, height)
][, .(
  mean = mean(height, na.rm = TRUE),
  median = median(height, na.rm = TRUE),
  N = .N,
  sd = sd(height, na.rm = TRUE)
), by = .(block, plot, duration)][, duration := factor(duration)]

ggboxplot(
  e2_height_summary,
  x = "duration",
  y = "median",
  color = "duration",
  add = "jitter"
) +
  labs(
    title = "Extension by Treatment",
    x = "Waterlogging duration (weeks)",
    y = "Height (cm)"
  )

# E2 height model
e2_height_model <- lmer(
  log(height) ~ duration + timepoint + duration:timepoint + (1 | block) + (1 | tree) + (1 | pot), # + (timepoint | tree),
  data = e2[!(health %in% top_removals), duration := factor(duration)]
)

# Check model assumptions
check_model(e2_height_model)

summary(e2_height_model)
Anova(e2_height_model, type = 3)


```

### Extension

```{r extension}

# Summarise feather
e2_feather_summary <- e2[
  !is.na(feather) & !(health %in% top_removals),
  .(block, plot, duration, feather)
][, .(
  feather = mean(feather, na.rm = TRUE),
  N = .N,
  sd = sd(feather, na.rm = TRUE)
), by = .(block, plot, duration)][, duration := factor(duration)]

ggboxplot(
  e2_feather_summary,
  x = "duration",
  y = "feather",
  color = "duration",
  add = "jitter"
) +
  labs(
    title = "Extension by Treatment",
    x = "Waterlogging duration (weeks)",
    y = "Extension (cm)"
  )

# E2 extension model
e2_extension_model <- lmer(
  log(feather) ~ duration + (1 | block) + (1 | pot),
  data = e2[!(health %in% top_removals)][, duration := factor(duration)]
)

# Check model assumptions
check_model(e2_extension_model)

summary(e2_extension_model)
Anova(e2_extension_model, type = 3)
emmeans(e2_extension_model, ~ duration)

```

## Canker

```{r canker}

# Summarise data by plot, taking the sum of canker measurements
e1_canker_summary <- e1[
  !is.na(cankers), .(block, plot, duration, cankers, inoc_points)
][, .(
  cankers = sum(cankers, na.rm = TRUE),
  inoc_points = sum(inoc_points, na.rm = TRUE),
  N = .N
), by = .(block, plot, duration)][, proportion := cankers / inoc_points]

# Quick boxplot of total_cankers by treatment

ggboxplot(e1_canker_summary, x = "duration", y = "proportion",
  color = "duration", palette = "jco",
  add = "jitter",
  title = "Total Cankers by Treatment",
  xlab = "Treatment", ylab = "Total Cankers"
) + theme(legend.position = "none")

e1_canker_model <- glmmTMB(
  cbind(inoc_cankers, inoc_points - inoc_cankers) ~ duration + (1 | block) + (1 | tree),
  family = betabinomial(link = "logit"),
  data = e1[!is.na(inoc_cankers)][, duration := factor(duration)]
)

# Check model assumptions
plot(simulateResiduals(e1_canker_model))

summary(e1_canker_model)
Anova(e1_canker_model, type = 3)
emmeans(e1_canker_model, ~ duration)

# E2 cankers

e2_canker_summary <- e2[
  !is.na(rasp_inoculations), .(
    block, plot, duration,
    rasp_cankers, rasp_inoculations
  )
][, .(
  rasp_cankers = sum(rasp_cankers, na.rm = TRUE),
  rasp_inoculations = sum(rasp_inoculations, na.rm = TRUE),
  N = .N
), by = .(block, plot, duration)][,
  proportion := rasp_cankers / rasp_inoculations
]

# Plot E2 cankers
ggboxplot(e2_canker_summary,
  x = "duration", y = "proportion",
  color = "duration", palette = "jco",
  add = "jitter",
  title = "Proportion of cankers by Treatment",
  xlab = "Waterlogging duration (weeks)", ylab = "Cankers per inoculation point"
) + theme(legend.position = "none")


e2_canker_model <- glmmTMB(
  cbind(rasp_cankers, rasp_inoculations - rasp_cankers) ~ duration + (1 | block) + (1 | tree) + (1 | pot),
  family = betabinomial(link = "logit"),
  data = e2[!is.na(rasp_cankers)][, duration := factor(duration)]
)

# Check model assumptions
sim <- simulateResiduals(e2_canker_model)
plot(sim)
testZeroInflation(sim)

summary(e2_canker_model)
Anova(e2_canker_model, type = 3)
emmeans(e2_canker_model, ~ duration)




# E3 cankers
e3_canker_summary <- e3[
  !is.na(rasp_inoculations) | !is.na(leaf_scar_inoculations),
  .(block, plot, treatment, genotype, rasp_inoculations, rasp_cankers, leaf_scar_inoculations, leaf_scar_cankers)
][, 
  .(
    rasp_cankers = sum(rasp_cankers, na.rm = TRUE),
    rasp_inoculations = sum(rasp_inoculations, na.rm = TRUE),
    leaf_scar_cankers = sum(leaf_scar_cankers, na.rm = TRUE),
    leaf_scar_inoculations = sum(leaf_scar_inoculations, na.rm = TRUE),
    N = .N
  ), 
  by = .(block, plot, treatment, genotype)
][, `:=`(
  rasp_proportion = rasp_cankers / rasp_inoculations,
  leaf_scar_proportion = leaf_scar_cankers / leaf_scar_inoculations
)]

# Plot E3 cankers
ggboxplot(e3_canker_summary,
  x = "treatment", y = "rasp_proportion",
  color = "genotype", palette = "jco",
  add = "jitter",
  title = "Proportion of rasp wound cankers by Treatment and Genotype",
  xlab = "Treatment", ylab = "Cankers per inoculation point"
) + theme(legend.position = "bottom")

ggboxplot(e3_canker_summary,
  x = "treatment", y = "leaf_scar_proportion",
  color = "genotype", palette = "jco",
  add = "jitter",
  title = "Proportion of leaf scar cankers by Treatment and Genotype",
  xlab = "Treatment", ylab = "Cankers per inoculation point"
) + theme(legend.position = "bottom")

```